name: amcharts
description: A Dart wrapper for AmCharts JS library.
version: 0.0.1
#author: Monty Rasmussen <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  js: any

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
